config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'about' => 'homes#about'
  resource :user, only: [:new, :create, :edit]
  get 'user/:id' => 'users#show', as: :user_show
  get 'users' => 'users#index', as: :index_user
  patch '/user' => 'users#update', as: :update_user
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resource :bookmarks, only: [:create, :destroy]
  get 'bookmarks' => 'bookmarks#index', as: :index_bookmaks

  resources :cookings, only: [:new, :create, :index, :edit, :update, :show, :destroy] do
    resources :cooking_comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  get 'rankings' => 'cookings#ranking', as: :cooking_rankings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :cooking
end

app/models/cooking.rb
class Cooking < ApplicationRecord
  attachment :cooking_image
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user
  has_many :cooking_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, length: { minimum: 3 }
  validates :cooking_introduction, length: { minimum: 5, maximum: 100 }
  validates :cooking_image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/cooking_comment.rb
class CookingComment < ApplicationRecord
  belongs_to :user
  belongs_to :cooking

  validates :comment, length: { minimum: 5 }
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1,
  }, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :cooking
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attachment :profile_image
  has_many :cookings, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :cooking_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, length: { minimum: 3 }
  validates :email, presence: true
  validates :introduction, length: { minimum: 5, maximum: 100 }
  validates :profile_image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def login?
    if current_user.nil?
      redirect_to login_path, alert: "ログインしてください"
    end
  end

  def already_login?
    unless current_user.nil?
      redirect_to user_show_path(current_user.id), notice: "すでにログインしています"
    end
  end

  def current_user
    if session[:user_id]
      current_user ||= User.find(session[:user_id])
    end
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :login?, only: [:index]

  def index
    @bookmarks = current_user.bookmarks
  end

  def create
    @bookmark = current_user.bookmarks.create(cooking_id: params[:cooking_id])
    flash[:success] = "この投稿をお気に入りに登録しました"
    redirect_to cooking_path(@bookmark.cooking.id)
  end

  def destroy
    @bookmark = current_user.bookmarks.find_by(id: params[:id]).destroy
    flash[:danger] = "この投稿のお気に入りを解除しました"
    redirect_to cooking_path(@bookmark.cooking.id)
  end
end

app/controllers/cooking_comments_controller.rb
class CookingCommentsController < ApplicationController
  def create
    @cooking = Cooking.find(params[:cooking_id])
    @cooking_comment = @cooking.cooking_comments.new(cooking_comment_params)
    @cooking_comment.user_id = current_user.id
    @cooking_comment.save
    redirect_to cooking_path(@cooking.id)
  end

  def destroy
    @cooking = Cooking.find(params[:cooking_id])
    @cooking_comment = CookingComment.find(params[:id])
    @cooking_comment.destroy
    redirect_to request.referer
  end

  private

  def cooking_comment_params
    params.require(:cooking_comment).permit(:comment, :rate)
  end
end

app/controllers/cookings_controller.rb
class CookingsController < ApplicationController
  before_action :login?, only: [:show, :new, :edit] # ログインしていないといけないようにする
  def new
    @cooking = Cooking.new
  end

  def index
    @cookings = Cooking.order("updated_at DESC")
    puts "作成したキー #{ENV['SECRET_KEY']}"
  end

  def create
    @cooking = Cooking.new(cooking_params)
    @cooking.user_id = current_user.id
    if @cooking.save
      redirect_to user_show_path(current_user.id)
    else
      render :new
    end
  end

  def edit
    @cooking = Cooking.find(params[:id])
  end

  def update
    @cooking = Cooking.find(params[:id])
    if @cooking.update(cooking_params)
      redirect_to cooking_path(@cooking.id)
    else
      render :edit
    end
  end

  def show
    @cooking = Cooking.find(params[:id])
    @cooking_comment = CookingComment.new
    @cooking_comments = @cooking.cooking_comments
    @bookmark = current_user.bookmarks.find_by(cooking_id: @cooking.id)
    @bookmarks = @cooking.bookmark_users
  end

  def destroy
    @cooking = Cooking.find(params[:id])
    @cooking.destroy
    redirect_to user_show_path(current_user.id)
  end

  def ranking
    @cookings = Cooking.find(CookingComment.group(:cooking_id).order('avg(rate) desc').pluck(:cooking_id))
  end

  private

  def cooking_params
    params.require(:cooking).permit(:cooking_image, :name, :cooking_introduction, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @cooking = Cooking.find(params[:cooking_id])
    @like = current_user.likes.new(cooking_id: @cooking.id)
    @like.save
    redirect_to request.referer
  end

  def destroy
    @cooking = Cooking.find(params[:cooking_id])
    @like = current_user.likes.find_by(cooking_id: @cooking.id)
    @like.destroy
    redirect_to request.referer
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_login?, except: :destroy

  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_show_path(user.id), notice: "ログインしました"
    else
      flash.now[:alert] = "メールアドレスまたはパスワードが間違っています"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, alert: "ログアウトしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_login?, only: [:new, :create]
  before_action :login?, only: :show

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save == true
      session[:user_id] = @user.id
      redirect_to user_show_path(@user.id), notice: "新規登録しました"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @cookings = @user.cookings
    @sum = 0
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_show_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/cooking_comments_helper.rb
module CookingCommentsHelper
end

app/helpers/cookings_helper.rb
module CookingsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/index.html.erb
<div class="pt-3">
  <font color="#FF6600"><div class="h2">Bookmarks</font></div>
</div>
<div class="row">
  <% @bookmarks.each do |bookmark| %>
  <div class="cooking col-md-3 pt-3 mb-3 border border-warning rounded">
    <div class="pb-3">
    <%= attachment_image_tag bookmark.cooking.user, :profile_image, :fill, 40, 40, format: 'jpeg', class:"rounded-circle"; %>
    <span class="ml-2"><%= bookmark.cooking.user.name %></span>
    </div>
    <div class="text-center">
      <%= attachment_image_tag bookmark.cooking, :cooking_image, :size => '200x150', fallback: "no_image.jpg"%>
    </div>
    <div class="card-body">
      <div>
        <%= bookmark.cooking.created_at.strftime('%Y/%m/%d') %>
      </div>
      <div class="pt-1">
        <i class="fas fa-utensils"></i><span class="ml-2"><%= link_to cooking_path(bookmark.cooking.id) do %><%= bookmark.cooking.name %><% end %></span>
      </div>
    </div>
  </div>
    <% end %>
</div>

app/views/cookings/edit.html.erb
<div class="row">
  <div class="col-lg-2">
  </div>
    <div class="col-lg-8 text-white pt-5">
      <% if @cooking.errors.any? %>
          <%#= @cooking.errors.count %>
          <% @cooking.errors.full_messages.each do |message| %>
            <div>
              <li><font color="red"><%= message %></font></li>
            </div>
          <% end %>
        <% end %>
      <div class="row">
        <div class="col-lg-6">
          <%= attachment_image_tag @cooking, :cooking_image, :fill, 250, 200, format: 'jpeg' %>
          <%= form_with model: @cooking, local: true do |f| %>
          <p>料理</p>
          <%= f.attachment_field :cooking_image %>
          <p>料理名</p>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
        </div>
        <div class="col-lg-6">
          <div class="pb-2">作り方</div>
          <%= f.text_area :cooking_introduction, size: "46x11" %>
          <div class="text-center">
            <%= f.submit '更新', class: "btn btn-success" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  <div class="col-lg-2">
  </div>
</div>

app/views/cookings/index.html.erb
<div class="pt-3">
  <font color="#FF6600"><div class="h2">Cookings</font></div>
</div>
<div class="row">
  <% @cookings.each do |cooking| %>
  <div class="cooking col-md-4 pt-3 mb-3 border border-warning rounded">
    <div class="pb-3">
      <%= attachment_image_tag cooking.user, :profile_image, :fill, 50, 50, format: 'jpeg', class:"rounded-circle"; %>
      <span class="ml-3"><%= cooking.user.name %></span>
    </div>
    <div class="text-center">
      <%= attachment_image_tag cooking, :cooking_image, :fill, 300, 250, format: 'jpeg' %>
    </div>
    <div class="card-body">
      <div>
        <%= cooking.updated_at.strftime('%Y/%m/%d') %>
        <span class="ml-3"><font color="#FFA500"><i class="fas fa-thumbs-up"></i></font></span><span class="ml-2"><%= cooking.likes.count %></span>
        <span class="ml-3"><font color="#4169E1	"><i class="far fa-comment-dots"></i></font></span><span class="ml-2"><%= link_to "#{cooking.cooking_comments.count}", cooking_path(cooking.id) %></span>
        <span class="ml-3"><img src="/assets/star-on.png" alt=""></span><span class="ml-2"><%= cooking.bookmarks.count %></span>
      </div>
      <div class="pt-1">
        <i class="fas fa-utensils"></i><span class="ml-2"><%= link_to cooking_path(cooking.id) do %><%= cooking.name %><% end %></span>
      </div>
      <div class="pt-1">
        評価 | <span class="mr-2"><%= cooking.cooking_comments.average(:rate).to_f.round(1) %></span><span id="star-rate-<%= cooking.id %>"></span>
      </div>
      <script>
        $('#star-rate-<%= cooking.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: '<%= cooking.cooking_comments.average(:rate).to_f.round(1) %>',
        });
      </script>
      </div>
    </div>
  <% end %>
  </div>

app/views/cookings/new.html.erb
<div class="row">
  <div class="col-lg-2">
  </div>
  <div class="col-lg-8 text-white pt-5">
        <% if @cooking.errors.any? %>
          <%= @cooking.errors.count %>件のエラーが発生しました
          <% @cooking.errors.full_messages.each do |message| %>
            <div>
              <li><font color="red"><%= message %></font></li>
            </div>
          <% end %>
        <% end %>
    <div class="row">
      <div class="col-lg-6">
        <%= form_with model: @cooking, local:true do |f| %>
          <p>料理投稿</p>
          <%= image_tag 'cooking_new.jpg', :size => '200x150' %>
          <p>料理</p>
          <%= f.attachment_field :cooking_image %>
          <p class="pt-2">料理名</p>
          <%= f.text_field :name %>
      </div>
      <div class="col-lg-6">
        <p>作り方</p>
        <%= f.text_area :cooking_introduction, size: "46x11" %>
        <div class="text-center">
          <%= f.submit '投稿する', class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
  <div class="col-lg-2">
  </div>
</div>

app/views/cookings/show.html.erb
<% if @cooking_comment.errors.any? %>
  <%= @cooking_comment.errors.count %>件のエラーが発生しました
  <% @cooking_comment.errors.full_messages.each do |message| %>
    <div>
      <li><font color="red"><%= message %></font></li>
    </div>
  <% end %>
<% end %>
<div class="row">
  <div class="col-md-6 pt-5">
    <div class="row">
      <div class="cooking col-md-6 pb-3 border border-warning rounded pt-3">
        <div class="pb-3">
          <%= attachment_image_tag @cooking.user, :profile_image, :fill, 50, 50, format: 'jpeg', class:"rounded-circle"; %>
          <span class="ml-2"><%= @cooking.user.name %></span>
        </div>
        <%= attachment_image_tag @cooking, :cooking_image, :fill, 250, 200, format: 'jpeg' %>
            <% unless @cooking.user_id == current_user.id %>
            <div class="pt-3 text-center">
            <div class="line-it-button" data-lang="ja" data-type="share-a" data-ver="3" data-url="https://social-plugins.line.me/ja/how_to_install#lineitbutton" data-color="default" data-size="small" data-count="false" style="display: none;"></div>
             <script src="https://www.line-website.com/social-plugins/js/thirdparty/loader.min.js" async="async" defer="defer"></script>

            <div id="fb-root"></div>
            <script async defer crossorigin="anonymous" src="https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v10.0" nonce="gTmNljCI"></script>
            <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">シェア</a></div>
            </div>
            <% end %>
            <div class="text-center pt-2">
              <span class="pr-5">
                <% if @cooking.user != current_user %> <% '投稿した人とログインしている人が一致しなかったら表示する' %>
                <% if Like.find_by(user_id: current_user.id, cooking_id: @cooking.id) %>
                    <%= link_to cooking_like_path(@cooking), method: :delete, class:"element", remote: true do %>
                      <i class="fas fa-thumbs-up"></i><span class="ml-2"><%= @cooking.likes.count %></span>
                    <% end %>
                  <% else %>
                    <%= link_to cooking_likes_path(@cooking), method: :post, class:"element", remote: true do %>
                      <i class="fas fa-thumbs-up"></i><span class="ml-2"><%= @cooking.likes.count %></span>
                    <% end %>
                <% end %>
                <% end %>
              </span>
              <% unless @cooking.user_id == current_user.id %>
                <% if @bookmark.present? %>
                      <%= link_to bookmarks_path(id: @bookmark.id), method: :delete, class: "btn btn-danger" do %><i class="far fa-star"></i> 解除<% end %>
                <% else %>
                      <%= link_to bookmarks_path(cooking_id: @cooking.id), method: :post, class:"btn btn-warning" do %><i class="far fa-star"></i> 登録<% end %>
                <% end %>
              <% end %>
            </div>
          <div class="text-center pt-2">
            <span class="pr-5"><% if @cooking.user == current_user %><%= link_to edit_cooking_path(@cooking.id), class: "btn btn-secondary", method: :get do %><i class="fas fa-pen"></i><% end %></span>
            <%= link_to "削除する", cooking_path(@cooking.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn-danger' %><% end %>
          </div>
        </div>
        <div class="cooking_introduction col-md-6 border border-warning rounded">
          <div class="pt-3">
            <%= @cooking.name %>
          </div>
          <div>
            <%= @cooking.cooking_introduction %>
          </div>
        </div>
    </div>
  <div class="py-2">
    <img src="/assets/star-on.png" alt=""><font color="white">お気に入りユーザー</font>
  </div>
  <div class="row">
  <% @bookmarks.each do |bookmark| %>
  <div class="col-md-3 text-center">
    <%= attachment_image_tag bookmark, :profile_image, :size => '100x100', fallback: "no_image.jpg"%>
    <div>
      <font color="white"><%= bookmark.name %></font>
    </div>
  </div>
  <% end %>
  </div>
  </div>
<div class="col-md-6 pt-5">
<% unless @cooking.user_id == current_user.id %>
  <%= form_with(model:[@cooking, @cooking_comment],local: true) do |f| %>

  <span id="rating-form">
        <label>評価：</label>
        <%# scoreNameの値をhidden_fieldでカラムに送っている %>
        <span><%= f.hidden_field :rate, id: :review_star %></span>
    </span>
  <div class="pb-2">
    <%= f.text_area :comment, size: "40x5" %>
    <%= f.submit '送信', class: "btn-sm btn-primary" %>
  </div>
  <script>
    $('#rating-form').raty({
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        scoreName: 'cooking_comment[rate]',
        half: true,
    });
  </script>

<% end %>
<% end %>

<table>
  <thead>
    <tr class="border-bottom text-center">
      <th>投稿日</th>
      <th>投稿者</th>
      <th width="210">コメント一覧</th>
      <th>評価</th>
      <th></th>
    </tr>
  </thead>
  <tbody class="text-white">
    <% @cooking_comments.each do |comment| %>
      <tr class="border-bottom">
        <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
        <td class="text-center"><%= comment.user.name %></td>
        <td><%= comment.comment %></td>
        <td><span id="star-rate-<%= comment.id %>"></span>
        <script>
          $('#star-rate-<%= comment.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= comment.rate %>,
          });
      </script>
        </td>
        <td><% if current_user && comment.user == current_user %>  <% 'コメントしたユーザーのみ、コメントの削除ができるようにします。'%>
            <%= link_to cooking_cooking_comment_path(@cooking, comment), method: :delete, class: 'btn btn-danger btn-sm' do %>削除<% end %>
            <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/homes/about.html.erb
<div class="text-center pt-5">
  <font color="#FF6600"><h3><span class="about">CookingBlog</span>へようこそ</h3></font>
  <div class="text-white pt-3">
    <P>このサイトでは皆さんの作っている料理を</P>
    <p>共有しあったりシェアをしたりして</p>
    <p>交流を深め合ったり通じ合っていくサイトです。</p>
  </div>
</div>

app/views/homes/top.html.erb
<div class="top text-center">
  <div style="height: 150px; width: auto;">
  </div>
  <font color="green"><p><%= alert %></p></font>
  <font color="#FF6600"><h1>Cooking Blog</h1>

  <h3>cooking personal community</h3></font>
  <div class="pt-3">
    <%= link_to "ログイン", login_path, class: "btn btn-outline-primary w-25" %>
  </div>
  <div class="pt-3">
    <%= link_to "新規登録", new_user_path, class: "btn btn-outline-success w-25" %>
  </div>
</div>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6 text-center text-white pt-5">
    <% if @user.errors.any? %>
    <%= @user.errors.count %>件のエラーが発生しました
    <% @user.errors.full_messages.each do |message| %>
      <div>
        <li><font color="red"><%= message %></font></li>
      </div>
    <% end %>
    <% end %>
    <%= form_with model: @user, url: update_user_path, local: true do |f| %>

      <%= attachment_image_tag @user, :profile_image, :size => '100x100', fallback: "no_image.jpg"%>

      <p>プロフィール画像</p>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>

      <p>名前</p>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" , class: "w-50" %>

      <p>メールアドレス</p>
      <%= f.text_field :email, autofocus: true, class: "w-50" %>

      <p>自己紹介文</p>
      <%= f.text_area :introduction, rows: 6 , class: "w-50" %><br>
      <div class="pt-2">
        <%= f.submit '更新', class: "btn btn-success w-25" %>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
  </div>
</div>

app/views/users/new.html.erb
<div class="mt-5 mb-3 text-center">
  <font color="red">
  </font>
</div>
<div class="row">
  <div class="col-lg-2">
  </div>
    <div class="col-lg-8">
      <% if @user.errors.any? %>
          <%#= @user.errors.count %>
          <% @user.errors.full_messages.each do |message| %>
            <div>
              <li><font color="red"><%= message %></font></li>
            </div>
          <% end %>
        <% end %>
      <div class="h3 text-center text-white pb-3">新規登録</div>
      <div class="row">
        <div class="col-lg-6 text-white">
          <%= form_with model: @user, url: user_path, local: true do |f| %>
          <%= image_tag 'cooking1.jpg', :size => '200x150' %>
          <div class="pt-2">
          プロフィール画像
          </div>
          <div class="pt-2">
          <%= f.attachment_field :profile_image %>
          </div>
          <div class="field">
            <%= f.label :名前 %><br>
            <%= f.text_field :name, :placeholder => "\uf007 名前" ,class: "form-control w-75 fa" %>
          </div>
          <div class="field">
            <%= f.label :メールアドレス %><br>
            <%= f.text_field :email, :placeholder => "\uf199 メールアドレス" ,class: "form-control w-75 fa" %>
          </div>
        </div>
        <div class="col-lg-6 text-white">
          <div class="field">
            <%= f.label :自己紹介文 %><br>
            <%= f.text_area :introduction, rows: 6 , :placeholder => "\uf2bb ここに自己PR文を入れてください" ,class: "form-control w-75 fa" %>
          </div>
          <div class="field">
            <%= f.label :パスワード %><br>
            <%= f.password_field :password, :placeholder => "\uf502 パスワード"  ,class: "form-control w-75 fa" %>
          </div>
          <div class="field">
            <%= f.label :パスワード（確認用） %><br>
            <%= f.password_field :password_confirmation ,class: "w-75" %>
          </div>
          <div class="mt-3">
            <%= f.submit "新規登録" ,class: "btn btn-success" %>
          </div>
          <div class="mt-2 pb-3">
            新規登録をされた方は<%= link_to "こちら>", login_path %>
          </div>
        </div>
      </div>
    </div>
  <div class="col-lg-2">
  </div>
</div>

<% end %>

app/views/users/show.html.erb
<% @cookings.each do |cooking| %>
  <% @sum += cooking.likes.count %>
<% end %>
<div class="text-center pt-3">
<font color="white">
  <%= notice %>
  <p class="pt-3">ようこそ"<strong><%= @user.name %></strong>"さん</p>
</font>
</div>
<div class="row">
  <div class="col-md-3 pt-3">
    <table class="table text-white">
      <tbody>
        <tr>
          <td><%= attachment_image_tag @user, :profile_image, :size => '100x100', fallback: "no_image.jpg" %></td>
        </tr>
        <tr>
          <td>名前 | <%= @user.name %></td>
        </tr>
        <tr>
          <td>Email | <%= @user.email %></td>
        </tr>
        <tr>
          <td>自己紹介文<br><%= @user.introduction %></td>
        </tr>
        <tr>
          <td><img src="/assets/star-on.png" alt="">お気に入り数<span class="ml-2"><%= current_user.bookmarks.count %></span></td>
        </tr>
        <tr>
          <td>いいねをもらった数<span class="ml-3"><font color="#FFA500"><i class="fas fa-thumbs-up"></i></font></span><span class="ml-2"><%= @sum %></span></td>
        </tr>
        <tr>
          <td><%= link_to edit_user_path , class: "btn btn-secondary", method: :get do %><i class="fas fa-wrench"></i><% end %>
              <%= link_to new_cooking_path , class: "btn btn-success", method: :get do %><i class="fas fa-utensils"></i> 投稿<% end %>
              <%= link_to index_bookmaks_path , class: "btn btn-warning", method: :get do %><i class="far fa-star"></i><% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-md-9 pt-3">
    <div class="row">
      <% @cookings.each do |cooking| %>
      <div class="cooking col-md-4 pt-4 border border-warning rounded">
        <div class="text-center">
          <%= attachment_image_tag cooking, :cooking_image, :size => '200x150' %>
        </div>
        <div class="card-body">
          <div>
          <%= cooking.created_at.strftime('%Y/%m/%d') %>
          </div>
          <div class="pt-1">
            <i class="fas fa-utensils"></i><span class="ml-2"><%= link_to cooking_path(cooking.id) do %><%= cooking.name %><% end %></span>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>