config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'about' => 'homes#about'
  resource :user, only: [:new, :create, :edit]
  get 'user/:id' => 'users#show', as: :user_show
  get 'users' => 'users#index', as: :index_user
  patch '/user' => 'users#update', as: :update_user
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resource :bookmarks, only: [:create, :destroy]
  get 'bookmarks' => 'bookmarks#index', as: :index_bookmaks

  resources :cookings, only: [:new, :create, :index, :edit, :update, :show, :destroy] do
    resources :cooking_comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  get 'rankings' => 'cookings#ranking', as: :cooking_rankings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :cooking
end

app/models/cooking.rb
class Cooking < ApplicationRecord
  attachment :cooking_image
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user
  has_many :cooking_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, length: { minimum: 3 }
  validates :cooking_introduction, length: { minimum: 5, maximum: 100 }
  validates :cooking_image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/cooking_comment.rb
class CookingComment < ApplicationRecord
  belongs_to :user
  belongs_to :cooking

  validates :comment, length: { minimum: 5 }
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1,
  }, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :cooking
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attachment :profile_image
  has_many :cookings, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :cooking_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, length: { minimum: 3 }
  validates :email, presence: true
  validates :introduction, length: { minimum: 5, maximum: 100 }
  validates :profile_image, presence: true
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :login?, only: [:index]

  def index
    @bookmarks = current_user.bookmarks
  end

  def create
    @bookmark = current_user.bookmarks.create(cooking_id: params[:cooking_id])
    flash[:success] = "この投稿をお気に入りに登録しました"
    redirect_to cooking_path(@bookmark.cooking.id)
  end

  def destroy
    @bookmark = current_user.bookmarks.find_by(id: params[:id]).destroy
    flash[:danger] = "この投稿のお気に入りを解除しました"
    redirect_to cooking_path(@bookmark.cooking.id)
  end
end

app/controllers/cookings_controller.rb
class CookingsController < ApplicationController
  before_action :login?, only: [:show, :new, :edit] # ログインしていないといけないようにする
  def new
    @cooking = Cooking.new
  end

  def index
    @cookings = Cooking.order("updated_at DESC")
    puts "作成したキー #{ENV['SECRET_KEY']}"
  end

  def create
    @cooking = Cooking.new(cooking_params)
    @cooking.user_id = current_user.id
    if @cooking.save
      redirect_to user_show_path(current_user.id)
    else
      render :new
    end
  end

  def edit
    @cooking = Cooking.find(params[:id])
  end

  def update
    @cooking = Cooking.find(params[:id])
    if @cooking.update(cooking_params)
      redirect_to cooking_path(@cooking.id)
    else
      render :edit
    end
  end

  def show
    @cooking = Cooking.find(params[:id])
    @cooking_comment = CookingComment.new
    @cooking_comments = @cooking.cooking_comments
    @bookmark = current_user.bookmarks.find_by(cooking_id: @cooking.id)
    @bookmarks = @cooking.bookmark_users
  end

  def destroy
    @cooking = Cooking.find(params[:id])
    @cooking.destroy
    redirect_to user_show_path(current_user.id)
  end

  def ranking
    @cookings = Cooking.find(CookingComment.group(:cooking_id).order('avg(rate) desc').pluck(:cooking_id))
  end

  private

  def cooking_params
    params.require(:cooking).permit(:cooking_image, :name, :cooking_introduction, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @cooking = Cooking.find(params[:cooking_id])
    @like = current_user.likes.new(cooking_id: @cooking.id)
    @like.save
    redirect_to request.referer
  end

  def destroy
    @cooking = Cooking.find(params[:cooking_id])
    @like = current_user.likes.find_by(cooking_id: @cooking.id)
    @like.destroy
    redirect_to request.referer
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_login?, except: :destroy

  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_show_path(user.id), notice: "ログインしました"
    else
      flash.now[:alert] = "メールアドレスまたはパスワードが間違っています"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, alert: "ログアウトしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_login?, only: [:new, :create]
  before_action :login?, only: :show

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save == true
      session[:user_id] = @user.id
      redirect_to user_show_path(@user.id), notice: "新規登録しました"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @cookings = @user.cookings
    @sum = 0
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_show_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/cooking_comments_helper.rb
module CookingCommentsHelper
end

app/helpers/cookings_helper.rb
module CookingsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookingBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-2 border" href="/"><%= image_tag 'cooking_image.jpg', :size =>'50x50' %></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
              <div class="collapse navbar-collapse" id="navbarnavDropdown">
                <ul class="navbar-nav ml-auto">
                <% if current_user %>
                  <li class="nav-item pr-2">
                    <%= link_to "マイページ", user_show_path(current_user.id), class: "btn btn-outline-primary" %>
                  </li>
                  <li class="nav-item pr-2">
                    <%= link_to "投稿一覧", cookings_path, class: "btn btn-outline-warning" %>
                  </li>
                  <li class="nav-item pr-2">
                    <%= link_to "ユーザー一覧", index_user_path, class: "btn btn-outline-success" %>
                  </li>
                  <li class="nav-item pr-2">
                    <%= link_to "ランキング", cooking_rankings_path, class: "btn btn-outline-warning" %>
                  </li>
                  <li class="nav-item pr-2">
                    <%= link_to "ログアウト", logout_path, method: :delete, class: "btn btn-outline-dark" %>
                  </li>
                <% else %>
                  <li class="nav-item pr-2">
                    <%= link_to "新規登録", new_user_path, class: "btn btn-outline-success" %>
                  </li>
                  <li class="nav-item pr-2">
                    <%= link_to "ログイン", login_path, class: "btn btn-outline-primary" %>
                  </li>
                  <li class="nav-item pr-2">
                    <%= link_to "投稿一覧", cookings_path, class: "btn btn-outline-warning" %>
                  </li>
                  <li class="nav-item pr-2">
                    <%= link_to 'About', about_path, class: "btn btn-outline-info" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>